# Docs for the Azure Web Apps Deploy action:
# https://github.com/Azure/webapps-deploy

name: Build and Deploy React App to Azure

on:
  push:
    branches:
      - main

  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:

      # =====================================
      # CHECKOUT CODE
      # =====================================
      - name: Checkout Repository
        uses: actions/checkout@v4

      # =====================================
      # NODE SETUP
      # =====================================
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      # =====================================
      # INSTALL DEPENDENCIES
      # =====================================
      - name: Install Dependencies
        run: npm install

      # =====================================
      # BUILD APP
      # =====================================
      - name: Build React App
        run: npm run build

      # =====================================
      # UPLOAD BUILD FILES
      # =====================================
      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: react-app
          path: dist

  deploy:

    runs-on: ubuntu-latest

    needs: build

    permissions:
      id-token: write
      contents: read

    steps:

      # =====================================
      # DOWNLOAD BUILD
      # =====================================
      - name: Download Build Artifact
        uses: actions/download-artifact@v4
        with:
          name: react-app
          path: .

      # =====================================
      # AZURE LOGIN
      # =====================================
      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_F47EA6D1058540D4A8DDEBAF894FFE89 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_F81636ACBA1A4D70AB373D6CF4F276E8 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_BE7E02EDC88D4CAFBC4296B305216E05 }}

      # =====================================
      # DEPLOY TO AZURE
      # =====================================
      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: certificategenerator
          slot-name: Production
          package: .
